apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ecommerce
  labels:
    app: ecommerce-database
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: ecommerce-database