apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
  namespace: ecommerce
  labels:
    app: ecommerce-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30090  # Frontend will be accessible on port 30090
    protocol: TCP
    name: http
  selector:
    app: ecommerce-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-internal
  namespace: ecommerce
  labels:
    app: ecommerce-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ecommerce-frontend
