apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  labels:
    app: ecommerce-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
      - name: frontend
        image: 10.34.100.141:5000/ecommerce-frontend:${BUILD_NUMBER}
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://10.34.100.141:30080"
        - name: VITE_MIDTRANS_CLIENT_KEY
          value: "SB-Mid-client-vZ1KhHbjaNBsy60c"
        - name: VITE_MIDTRANS_ENVIRONMENT
          value: "sandbox"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
spec:
  type: NodePort
  selector:
    app: ecommerce-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081