services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ecommerce_frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - ecommerce_net

networks:
  ecommerce_net:
    name: back-end_ecommerce_net
    external: true
