version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ecommerce-frontend-dev
    environment:
      VITE_API_URL: http://localhost:8080
      VITE_MIDTRANS_CLIENT_KEY: your-midtrans-client-key
      VITE_MIDTRANS_ENVIRONMENT: sandbox
    ports:
      - "3000:80"
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    external: true
