services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart : always
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: db_ecommerce
    restart : always
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: