services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ecommerce_backend
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ecommerce_net

  db:
    image: mariadb:latest
    container_name: db_ecommerce
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_net

volumes:
  mysql_data:

networks:
  ecommerce_net:
    driver: bridge