apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: ecommerce
data:
  MARIADB_DATABASE: "ecommerce"
  MARIADB_USER: "ecommerce_user"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - change these in production
  MARIADB_PASSWORD: ZWNvbTEyMw==
  MARIADB_ROOT_PASSWORD: ZWNvbTEyMw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-database
  namespace: ecommerce
  labels:
    app: ecommerce-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-database
  template:
    metadata:
      labels:
        app: ecommerce-database
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MARIADB_DATABASE
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MARIADB_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: MARIADB_PASSWORD
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: MARIADB_ROOT_PASSWORD
        # MariaDB memory optimization settings
        args:
          - --innodb-buffer-pool-size=64M
          - --innodb-log-file-size=16M
          - --innodb-log-buffer-size=4M
          - --query-cache-size=16M
          - --thread-cache-size=4
          - --max-connections=50
          - --table-open-cache=128
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "128Mi"  # Reduced from 256Mi
            cpu: "100m"      # Reduced from 250m
          limits:
            memory: "256Mi"  # Reduced from 512Mi
            cpu: "300m"      # Reduced from 500m
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 60  # Increased for slower startup
          periodSeconds: 20        # Less frequent checks
          failureThreshold: 5      # More tolerant
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-sql
        configMap:
          name: init-sql-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Reduced from 2Gi to save disk space
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
  namespace: ecommerce
data:
  init.sql: |
    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8mb4 */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    -- Create database
    CREATE DATABASE IF NOT EXISTS ecommerce;
    USE ecommerce;

    DROP TABLE IF EXISTS `cart_items`;
    CREATE TABLE `cart_items` (
      `id` varchar(36) NOT NULL,
      `user_id` varchar(36) NOT NULL,
      `product_id` varchar(36) NOT NULL,
      `quantity` bigint(20) NOT NULL,
      `created_at` datetime(3) DEFAULT NULL,
      `updated_at` datetime(3) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `fk_cart_items_user` (`user_id`),
      KEY `fk_cart_items_product` (`product_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    DROP TABLE IF EXISTS `categories`;
    CREATE TABLE `categories` (
      `id` varchar(36) NOT NULL,
      `name` varchar(255) NOT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `uni_categories_name` (`name`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    DROP TABLE IF EXISTS `users`;
    CREATE TABLE `users` (
      `id` varchar(36) NOT NULL,
      `name` varchar(255) NOT NULL,
      `email` varchar(255) NOT NULL,
      `password` longtext NOT NULL,
      `role` enum('admin','seller','buyer') DEFAULT 'buyer',
      `created_at` datetime(3) DEFAULT NULL,
      `updated_at` datetime(3) DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `uni_users_email` (`email`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    DROP TABLE IF EXISTS `products`;
    CREATE TABLE `products` (
      `id` varchar(36) NOT NULL,
      `name` varchar(255) NOT NULL,
      `description` text DEFAULT NULL,
      `price` double NOT NULL,
      `stock` bigint(20) NOT NULL,
      `image_url` text DEFAULT NULL,
      `seller_id` varchar(36) NOT NULL,
      `category_id` varchar(36) NOT NULL,
      `created_at` datetime(3) DEFAULT NULL,
      `updated_at` datetime(3) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `fk_users_products` (`seller_id`),
      KEY `fk_categories_products` (`category_id`),
      CONSTRAINT `fk_categories_products` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`),
      CONSTRAINT `fk_users_products` FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    DROP TABLE IF EXISTS `orders`;
    CREATE TABLE `orders` (
      `id` varchar(36) NOT NULL,
      `user_id` varchar(36) NOT NULL,
      `total_price` double NOT NULL,
      `status` enum('pending','paid','shipped','completed','cancelled') DEFAULT 'pending',
      `created_at` datetime(3) DEFAULT NULL,
      `updated_at` datetime(3) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `fk_users_orders` (`user_id`),
      CONSTRAINT `fk_users_orders` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    DROP TABLE IF EXISTS `order_items`;
    CREATE TABLE `order_items` (
      `id` varchar(36) NOT NULL,
      `order_id` varchar(36) NOT NULL,
      `product_id` varchar(36) NOT NULL,
      `quantity` bigint(20) NOT NULL,
      `price` double NOT NULL,
      PRIMARY KEY (`id`),
      KEY `fk_order_items_product` (`product_id`),
      KEY `fk_orders_order_items` (`order_id`),
      CONSTRAINT `fk_order_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
      CONSTRAINT `fk_orders_order_items` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    DROP TABLE IF EXISTS `payments`;
    CREATE TABLE `payments` (
      `id` varchar(36) NOT NULL,
      `order_id` varchar(36) NOT NULL,
      `amount` bigint(20) NOT NULL,
      `snap_token` longtext NOT NULL,
      `transaction_id` longtext DEFAULT NULL,
      `status` varchar(20) NOT NULL DEFAULT 'pending',
      `created_at` datetime(3) DEFAULT NULL,
      `updated_at` datetime(3) DEFAULT NULL,
      `deleted_at` datetime(3) DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `idx_payments_order_id` (`order_id`),
      KEY `idx_payments_deleted_at` (`deleted_at`),
      CONSTRAINT `fk_payments_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    DROP TABLE IF EXISTS `reviews`;
    CREATE TABLE `reviews` (
      `id` varchar(36) NOT NULL,
      `user_id` varchar(36) NOT NULL,
      `product_id` varchar(36) NOT NULL,
      `rating` bigint(20) NOT NULL,
      `comment` text DEFAULT NULL,
      `created_at` datetime(3) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `fk_products_reviews` (`product_id`),
      KEY `fk_users_reviews` (`user_id`),
      CONSTRAINT `fk_products_reviews` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
      CONSTRAINT `fk_users_reviews` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

    -- Add foreign key constraints for cart_items (after all tables are created)
    ALTER TABLE `cart_items` 
    ADD CONSTRAINT `fk_cart_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
    ADD CONSTRAINT `fk_cart_items_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;

    -- Insert sample data
    INSERT INTO `users` (`id`, `name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES
    ('96ec37f4-a608-41ee-b942-5439f0294308', 'buyerr', 'buyerr123@gmail.com', '$2a$10$iamP.a/CF7qYQF9uri0N.eukdxEQ1NJB6xjOj..Mfx9.04OrR667y', 'buyer', '2025-04-08 03:54:34.250', '2025-04-08 03:54:34.250');

    -- Add sample admin user for testing
    INSERT INTO `users` (`id`, `name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES
    ('admin-001', 'Admin User', 'admin@ecommerce.com', '$2a$10$iamP.a/CF7qYQF9uri0N.eukdxEQ1NJB6xjOj..Mfx9.04OrR667y', 'admin', NOW(), NOW());

    -- Add sample seller for testing
    INSERT INTO `users` (`id`, `name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES
    ('seller-001', 'Seller User', 'seller@ecommerce.com', '$2a$10$iamP.a/CF7qYQF9uri0N.eukdxEQ1NJB6xjOj..Mfx9.04OrR667y', 'seller', NOW(), NOW());

    -- Add sample categories
    INSERT INTO `categories` (`id`, `name`) VALUES
    ('cat-001', 'Electronics'),
    ('cat-002', 'Clothing'),
    ('cat-003', 'Books'),
    ('cat-004', 'Home & Garden');

    -- Add sample products
    INSERT INTO `products` (`id`, `name`, `description`, `price`, `stock`, `image_url`, `seller_id`, `category_id`, `created_at`, `updated_at`) VALUES
    ('prod-001', 'Sample Laptop', 'High-performance laptop for developers', 15000000, 10, 'https://example.com/laptop.jpg', 'seller-001', 'cat-001', NOW(), NOW()),
    ('prod-002', 'Cotton T-Shirt', 'Comfortable cotton t-shirt', 150000, 50, 'https://example.com/tshirt.jpg', 'seller-001', 'cat-002', NOW(), NOW());

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;