apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ecommerce
data:
  VITE_API_URL: "http://10.34.100.141:30080"
  NODE_ENV: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: ecommerce
  labels:
    app: ecommerce-frontend
spec:
  replicas: 1  # Reduced from 2 to save memory
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
      - name: frontend
        image: 10.34.100.141:30500/ecommerce-frontend:${BUILD_NUMBER}
        ports:
        - containerPort: 3000
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_API_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NODE_ENV
        resources:
          requests:
            memory: "32Mi"   # Reduced from 128Mi
            cpu: "25m"       # Reduced from 100m
          limits:
            memory: "64Mi"   # Reduced from 256Mi
            cpu: "100m"      # Reduced from 200m
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 45  # Increased for slower startup
          periodSeconds: 15        # Less frequent checks
          failureThreshold: 5      # More tolerant
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always