apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
  namespace: ecommerce
  labels:
    app: ecommerce-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30090
    protocol: TCP
    name: http
  selector:
    app: ecommerce-frontend